### PR TITLE
MTM-42977: fixed notification2 url, added dependency

### PR DESCRIPTION
**Pull request by kacperterebus-sag**

### CODE REVIEW

**Review by andrekramer1 — APPROVED** [review]

**Review by scmi-c8y — COMMENTED** [review]
Just some very general comments as I don't feel I know this area of the code well enough to approve it - @ianfairman-sg @rohitjoshi-softwareag @gapa-c8y, hopefully one of you is able to approve?

1. You probably saw this already but you need to re-sync with develop.
2. For everyone, probably a good retrospective topic: _please add a useful description (and delete any irrelevant boilerplate cruft) when creating PRs_. It makes it much easier to review them if you have some idea of what the intention of the changes is.  A couple of bullet points and a link back to the Jira ticket would be sufficient in most cases.

**Review by rohitjoshi-c8y — APPROVED** [review]

**Comment by andrekramer1** [comment]
Needs to be backwards compatible and do we need the same change for tokenAPI?

**Comment by andrekramer1** [comment]
I think we need to do a similar change to TokenApi - in TokenApiImpl 
  private String getTokenRequestUri() {
        return platformParameters.getHost() + TOKEN_REQUEST_URI;
    }
Similar to what is proposed to sunbscriptions:
 private String getSelfUri() throws SDKException {
        - return restConnector.getPlatformParameters().getHost() + SUBSCRIPTION_REQUEST_URI;
        + return notificationApiRepresentation.getNotificationSubscriptions().getSelf();
    }

**Comment by andrekramer1** [comment]
This change is not backwards compatible. We would need to check for null which is returned until we make core changes to return the subscription api URL. Also should do this for notifications (as other comment already notes).

**Comment by andrekramer1** [comment]
This change is not backwards compatible. We would need to check for null which is returned until we make core changes to return the subscription api URL. Also should do this for notifications (as other comment already notes).

**Comment by andrekramer1** [comment]
This change is not backwards compatible. We would need to check for null which is returned until we make core changes to return the subscription api URL. Also should do this for notifications (as other comment already notes).

**Comment by kaczynskid-sag** [comment]
Closing as outdated

**Pull request closed without merging**
