### PR TITLE
MTM-49962 - remove cep esper tests

### PR DESCRIPTION
**Pull request by d-mariak**

### CODE REVIEW

**Comment by ghost** [comment]
Not sure if we should remove all the CEP api yet

**Review by ghost — DISMISSED** [review]

**Review by kaczynskid-sag — DISMISSED** [review]

**Review by c8y-kh4mell — DISMISSED** [review]

**Review by jkot-c8y — DISMISSED** [review]

**Comment by mbak-c8y** [comment]
probably we should also remove: src/integration-test/resources/cep/test-module.epl

**Comment by d-mariak** [comment]
> Not sure if we should remove all the CEP api yet

done

**Comment by d-mariak** [comment]
> Not sure if we should remove all the CEP api yet

reverted changes. Only tests will be removed.

**Review by jkot-c8y — APPROVED** [review]

**Review by mbak-c8y — APPROVED** [review]

**Pull request merged**
